services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: spotlight:prod
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"
    env_file:
      - .env.production.local
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start-watch
