services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      NODE_ENV: development
      PORT: 2999
    ports:
      - "2999:2999"
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start-watch
