services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: spotlight:dev
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    env_file:
      - .env.development.local
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start-watch
